apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  matchLabels:
    app: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
        image: nginx:latest
        ports:
          - containerPort: 80

